#pragma once

//#define CAPS_WORD_IDLE_TIMEOUT 3000

//#define RETRO_TAPPING
//#define PERMISSIVE_HOLD
#define HOLD_ON_OTHER_KEY_PRESS
// #define HOLD_ON_OTHER_KEY_PRESS
//#define TAPPING_TERM 180

#define ENABLE_COMPILE_KEYCODE


#define LEADER_TIMEOUT 300
#define LEADER_PER_KEY_TIMING
#define LEADER_NO_TIMEOUT

//#define UNICODE_SELECTED_MODES UNICODE_MODE_WINCOMPOSE
